trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

stages:
  - stage: PRValidation
    displayName: 'Run on Pull Request'
    jobs:
      - job: ValidatePR
        displayName: 'Validate Pull Request'
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - script: |
              echo "This job runs only for pull requests."
            displayName: 'Run Validation'
# ------------

# Explanation
# trigger:

# Ensures the pipeline runs on specific branches for other events (e.g., pushes).
# pr:

# Explicitly specifies which branches should trigger the pipeline for pull requests.
# condition:

# The condition eq(variables['Build.Reason'], 'PullRequest') ensures that the job runs only if the pipeline is triggered by a pull request.
# Steps:

# The job performs actions only when the condition is met.
# Other Build.Reason Values
# If you want to expand conditions for other scenarios, here are the possible values of Build.Reason:

# Manual: Triggered manually by a user.
# PullRequest: Triggered by a pull request.
# Schedule: Triggered by a scheduled run.
# BuildCompletion: Triggered by the completion of another build.
# ResourceTrigger: Triggered by a pipeline resource.